/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datavalidationsystem;

import javax.swing.JLabel;
import java.awt.Color;
import static java.awt.Color.red;
import javax.swing.JOptionPane;

/**
 *
 * @author brian
 */
public class validation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(validation.class.getName());

    /**
     * Creates new form validation
     */
    public validation() {
        initComponents();
        
        
        
        IbIResultName.setText("");
        IbIResultID.setText("");
        IbIResultAge.setText("");
        IbIResultGender.setText("");
        IbIResultNumber.setText("");
        IbIResultEmail.setText("");
        
    }
    
    private void validated(JLabel label, String message) {
    label.setText(message);
    label.setForeground(Color.GREEN);
}
    private void notValid(JLabel label, String message) {
    label.setText(message);
    label.setForeground(Color.RED);
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        headTxt = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        birthLbl = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        numberLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        birthTxt = new javax.swing.JTextField();
        numberTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IbIResultName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IbIResultID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IbIResultAge = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IbIResultGender = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IbIResultNumber = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        IbIResultEmail = new javax.swing.JLabel();
        nameVal = new javax.swing.JLabel();
        birthVal = new javax.swing.JLabel();
        numberVal = new javax.swing.JLabel();
        addressVal = new javax.swing.JLabel();
        genderVal = new javax.swing.JLabel();
        idVal = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JToggleButton();
        clearBtn = new javax.swing.JToggleButton();
        exitBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setBackground(new java.awt.Color(0, 102, 102));

        headTxt.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        headTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/glass.png"))); // NOI18N
        headTxt.setText("Static Data");
        headTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLbl.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLbl.setText("Full Name");

        idLbl.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        idLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLbl.setText("ID/Student number");

        birthLbl.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        birthLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birthLbl.setText("Age");

        genderLbl.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        genderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderLbl.setText("Gender");

        numberLbl.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        numberLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLbl.setText("Contact Number");

        emailLbl.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLbl.setText("Email Address");

        nameTxt.addActionListener(this::nameTxtActionPerformed);

        birthTxt.addActionListener(this::birthTxtActionPerformed);

        numberTxt.addActionListener(this::numberTxtActionPerformed);

        emailTxt.addActionListener(this::emailTxtActionPerformed);

        idTxt.addActionListener(this::idTxtActionPerformed);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESULTS");

        IbIResultName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IbIResultName.setForeground(new java.awt.Color(255, 255, 255));
        IbIResultName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name:");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID/Student ID:");

        IbIResultID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IbIResultID.setForeground(new java.awt.Color(255, 255, 255));
        IbIResultID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age:");

        IbIResultAge.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IbIResultAge.setForeground(new java.awt.Color(255, 255, 255));
        IbIResultAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender:");

        IbIResultGender.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IbIResultGender.setForeground(new java.awt.Color(255, 255, 255));
        IbIResultGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact Number:");

        IbIResultNumber.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IbIResultNumber.setForeground(new java.awt.Color(255, 255, 255));
        IbIResultNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email Address:");

        IbIResultEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IbIResultEmail.setForeground(new java.awt.Color(255, 255, 255));
        IbIResultEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IbIResultEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IbIResultNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IbIResultAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IbIResultID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IbIResultName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IbIResultGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(IbIResultName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(IbIResultID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IbIResultAge, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(11, 11, 11)))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(IbIResultGender, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(IbIResultNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IbIResultEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        maleRadio.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        maleRadio.setText("Male");
        maleRadio.addActionListener(this::maleRadioActionPerformed);

        femaleRadio.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        femaleRadio.setText("Female");
        femaleRadio.addActionListener(this::femaleRadioActionPerformed);

        saveBtn.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        clearBtn.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(this::clearBtnActionPerformed);

        exitBtn.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(this::exitBtnActionPerformed);

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bodyLayout.createSequentialGroup()
                                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                                .addGroup(bodyLayout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(nameTxt)))
                                            .addGroup(bodyLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(nameVal, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(157, 157, 157)
                                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(idTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(idLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(idVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(bodyLayout.createSequentialGroup()
                                        .addGap(367, 367, 367)
                                        .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(bodyLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(numberVal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(addressVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(birthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(birthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(birthVal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(genderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(femaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addComponent(genderVal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(saveBtn)
                        .addGap(154, 154, 154)
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn)
                        .addGap(136, 136, 136))
                    .addComponent(headTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(headTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameVal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idVal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(genderVal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberVal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressVal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bodyLayout.createSequentialGroup()
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maleRadio)
                                    .addComponent(birthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(femaleRadio)
                                    .addComponent(birthVal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void numberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTxtActionPerformed

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioActionPerformed

    private void femaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
      /*  String name = nameTxt.getText();
        if(name.isEmpty()){
            notValid(nameVal, "Empty field");
        }
        
        else if(name != null && name.matches("[a-zA-Z]+")){
            notValid(nameVal,"Letters Only");
            
        }
        
        else if(name.length() < 2 || name.length() > 30){
            notValid(nameVal, "Enter a valid full name");
        }
        else{
            validated(nameVal,"Valid");
        }*/
    }//GEN-LAST:event_nameTxtActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
      /*  String id = idTxt.getText();
        if (id.isEmpty()) {
            notValid(idVal,"Field Empty");
            return;
        }
        
        else if(id != null && !id.matches("\\d+")){
            notValid(idVal,"Use Numbers only");
        }
        
        else if (id.length() != 13){
            notValid(idVal,"Enter valid ID");
        }
        
        else{
            validated(idVal,"Valid");
        }
     */   
    }//GEN-LAST:event_idTxtActionPerformed

    private void birthTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthTxtActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        
        nameTxt.setText("");
    idTxt.setText("");
    birthTxt.setText("");
    numberTxt.setText("");
    emailTxt.setText("");
    
    maleRadio.setSelected(false);
    femaleRadio.setSelected(false);
    
    nameVal.setText("");
    idVal.setText("");
    birthVal.setText("");
    numberVal.setText("");
    addressVal.setText("");
    genderVal.setText("");
    
    IbIResultName.setText("");
    IbIResultID.setText("");
    IbIResultAge.setText("");
    IbIResultNumber.setText("");
    IbIResultEmail.setText("");
    IbIResultGender.setText("");
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void nameValid(){
        String name = nameTxt.getText();
        if (name.isEmpty()) {
            nameVal.setText("Field is empty");
            nameVal.setForeground(Color.red);
           
        }
        
        else if(name.matches("[a-zA-Z]+") && name.length() >=3){
            nameVal.setText("VALID");
            nameVal.setForeground(Color.green);
            IbIResultName.setText(name);
            
        }
        
        else if(name.length() < 2 || name.length() > 30){
            nameVal.setText("Enter a valid full name");
            nameVal.setForeground(Color.red);
            
        }
        
    }
    
    private void idValid(){
        String id = idTxt.getText();
        
        if (id.isEmpty()){
            idVal.setText("Field is empty");
            idVal.setForeground(Color.red);
        }
        
        else if(!id.matches("\\d+")){
            
            idVal.setText("Invalid");
            idVal.setForeground(Color.red);
        }
        
        else if(id.length() != 13)
        {
            idVal.setText("13 No. ID");
            idVal.setForeground(Color.red);
        }
        
        else{
            idVal.setText("Valid");
            idVal.setForeground(Color.green);
            IbIResultID.setText(id);
        }
        
    }
    
    private void ageValid(){
     String age = birthTxt.getText();
        
     //int ages = Integer.parseInt(birthTxt);
        
        
        if(age.isEmpty()){
            birthVal.setText("Field is empty");
            birthVal.setForeground(Color.red);
        }
        
        else if(!age.matches("\\d+")){
            birthVal.setText("Use Numbers");
            birthVal.setForeground(Color.red);
            
        }
        else{
            birthVal.setText("Valid");
            birthVal.setForeground(Color.green);
            IbIResultAge.setText(age);
        }
    }
    
    private void genderValid(){
        String gender = maleRadio.getText();
        
        
        
        if(gender.isEmpty()){
        genderVal.setText("Field is empty");
        genderVal.setForeground(Color.red);
        }
        
        else if(maleRadio.isSelected()){
            genderVal.setText("Male Selected");
            genderVal.setForeground(Color.green);
            IbIResultGender.setText(gender);
    }
        else if(femaleRadio.isSelected()){
            genderVal.setText("Female Selected");
            genderVal.setForeground(Color.green);
            IbIResultGender.setText(gender);
        }
        
        else if(femaleRadio.isSelected() && maleRadio.isSelected()){
            genderVal.setText("Select 1 Gender");
            genderVal.setForeground(Color.red);
        }
    }
    
    private void numberValid(){
        String number = numberTxt.getText();
        
        if(number.isEmpty()){
            numberVal.setText("Field is empty ");
            numberVal.setForeground(Color.red);
        }
        
        else if(!number.matches("\\d+")){
            numberVal.setText("Enter a number");
            numberVal.setForeground(Color.red);
        }
        
        else if(number.length() != 10){
            numberVal.setText("Enter 10 digit number");
            numberVal.setForeground(Color.red);
        }
        
        else{
            numberVal.setText("Valid");
            numberVal.setForeground(Color.green);
            IbIResultNumber.setText(number);
            
        }
    }
    
    private void emailValid(){
        String email = emailTxt.getText();
        
        if(email.isEmpty()){
            addressVal.setText("Field is empty");
            addressVal.setForeground(Color.red);
        }
        
        else if(email.contains("@gmail.com")){
            addressVal.setText("Valid");
            addressVal.setForeground(Color.green);
            IbIResultEmail.setText(email);
        }
        
        else{
            addressVal.setText("invalid");
            addressVal.setForeground(Color.red);
        }
    }
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        
        nameValid();
        idValid();
        ageValid();
        genderValid();
        numberValid();
        emailValid();
        
        //Results
        /*
        IbIResultName.setText(name);
        IbIResultID.setText(id);
        IbIResultAge.setText(age);
        IbIResultGender.setText(gender);
        IbIResultNumber.setText(number);
        IbIResultEmail.setText(email);
        */
        
        
        
        
        
        
        
        

        
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new validation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbIResultAge;
    private javax.swing.JLabel IbIResultEmail;
    private javax.swing.JLabel IbIResultGender;
    private javax.swing.JLabel IbIResultID;
    private javax.swing.JLabel IbIResultName;
    private javax.swing.JLabel IbIResultNumber;
    private javax.swing.JLabel addressVal;
    private javax.swing.JLabel birthLbl;
    private javax.swing.JTextField birthTxt;
    private javax.swing.JLabel birthVal;
    private javax.swing.JPanel body;
    private javax.swing.JToggleButton clearBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JToggleButton exitBtn;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JLabel genderVal;
    private javax.swing.JLabel headTxt;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel idVal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel nameVal;
    private javax.swing.JLabel numberLbl;
    private javax.swing.JTextField numberTxt;
    private javax.swing.JLabel numberVal;
    private javax.swing.JToggleButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
